### ISSUE TITLE
Is it possible to add react to this theme boilerplate?

### ISSUE THREAD

**Issue by StefanGhiban** [Cloudhuset/Zendesk-Guide-Theme-Boilerplate#8]

**Comment by Herlevsen** [comment]
Hi @StefanGhiban,

What would you use React for in Zendesk Guide? Guide is server rendered with their own template language, Curlybars. I don't see how React could fit well into this. Can you elaborate on your use case?

**Comment by StefanGhiban** [comment]
I wanted to make a theme for the help center using React to create an SPA.

**Comment by Herlevsen** [comment]
It's not possible to use React in Zendesk Guide. As i said, they are using Curlybars to render server side. So if you want to use React, you will need to render everything client side, and fetch the data via the api (or render the data as json via curlybars, but that will be a pain). This will also be bad for SEO, so i will strongly advise you not to go down that route.

It would be cool if Zendesk supported React for Guide, but I don't think that will happen anytime soon :-)

**Comment by StefanGhiban** [comment]
Thank you!
